### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by epsooraj** [cjpurackal/shapes#10]
Command
`python run.py --save_dir /tmp/ --image_size 500 500 --num_images 5 --shapes circle rect --shuffle_color True --task_type segmentation`

Returns an error

`Traceback (most recent call last):`
`File "run.py", line 203, in <module>`
`    segmentation_gen()`
`File "run.py", line 196, in segmentation_gen`
`    recognition_gen()`
`File "run.py", line 160, in recognition_gen`
`    if list(shape_attribs.keys())[obj_i] == "rect":`
`IndexError: list index out of range`

The above error occurs when using arguments 
`--task_type segmentation`
`--task_type recognition`

And no errors with the argument `--task_type detection`

**Comment by cjpurackal** [comment]
solved in #11
